In [1]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

# 1. Работа с массивами NumPy

**N. Все упражнения ниже нужно делать без использования циклов Python**

**1.** Cоздать вектор

$$(2, \frac{2^2}{2}, \ldots, \frac{2^{20}}{20})$$

Можно использовать функции [np.arange()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html), [np.ones()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html)

In [2]:
def f(i):
    return (2 ** (i + 1)) / (i + 1)

In [3]:
np.fromfunction(f, (20,))

array([2.00000000e+00, 2.00000000e+00, 2.66666667e+00, 4.00000000e+00,
       6.40000000e+00, 1.06666667e+01, 1.82857143e+01, 3.20000000e+01,
       5.68888889e+01, 1.02400000e+02, 1.86181818e+02, 3.41333333e+02,
       6.30153846e+02, 1.17028571e+03, 2.18453333e+03, 4.09600000e+03,
       7.71011765e+03, 1.45635556e+04, 2.75941053e+04, 5.24288000e+04])

**2.** Посчитать:

$$\sum\limits_{i=0}^{5}{0.1^{3i}0.2^{4i}}$$


In [4]:
def f(i):
    return 0.1 ** (3 * i) * 0.2 ** (4 * i)

In [5]:
sum(np.fromfunction(f, (6,)))

1.00000160000256

**3.** Создать нулевую матрицe $8 \times 8$, и заполнить её единицами в шахматном порядке.

In [6]:
x = np.tile(np.array([[0,1],[1,0]]), (4,4))
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


**4.** Есть 5 точек в декартовой системе координат (в виде матрицы $X$ размерностью $5 \times 2$), сконвертируйте эти точки в полярную систему координат.

In [7]:
X = np.random.random((5, 2))
a, b = X[:,0], X[:,1]
R = np.hypot(a, b)
Fi = np.arctan2(b, a)
print(R)
print(Fi)

[0.41193097 1.16067041 0.7610001  0.93667018 0.86541466]
[1.54489887 0.66674445 0.54888137 1.45990445 0.23419432]


**5.** Найдите индексы максимального элемента в случайной матрице $10 \times 10$.

Cм. [np.argmax()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.argmax.html).

In [8]:
X = np.random.random((10, 10))
ind = (np.argmax(X) // 10, np.argmax(X) % 10)
ind

(6, 2)

In [9]:
X[ind]

0.9927401975472885

**6.** Есть 10 точек ($X$) и ещё одна ($y$). Найти в $X$ ближайшую к $y$ точку.

In [10]:
X = np.random.random((10, 2))
y = np.random.random((1, 2))
d0 = np.subtract.outer(X[:,0], y[:,0])
d1 = np.subtract.outer(X[:,1], y[:,1])
np.argmin(np.hypot(d0, d1))

2

**7.** Дана функция:

$$
 \begin{cases}
    x^2 + 2x + 6, & x < 0  \\
    x + 6, & 0 \le x \le 2 \\
    x^2 + 4x - 4, & x \ge 2
 \end{cases}
$$

Постройте массив из её значений на  $-3 \le x \le 3$.

In [11]:
def f(i):
    if i < 0:
        return i ** 2 + 2 * i + 6
    elif i > 2 and i >= 0:
        return i ** 2 + 4 * i - 4
    else:
        return i + 6

In [12]:
rang = np.arange(-3, 4)
rang

array([-3, -2, -1,  0,  1,  2,  3])

In [13]:
np.array(list(map(f, rang)))

array([ 9,  6,  5,  6,  7,  8, 17])

**8.** Из каждого элемента матрицы вычесть среднее арифметическое от всех элементов в соответствующей строке (после чего среднее значение каждой строки должно равняться нулю).

Cм. [np.mean()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.mean.html).

In [14]:
X = np.random.random((10, 10))

In [15]:
res = X - np.mean(X, axis=1).reshape(10, 1)
res

array([[ 0.34970666,  0.22463637, -0.26814584,  0.01255666, -0.06027361,
        -0.30790766, -0.24085744,  0.53152333,  0.03263043, -0.27386889],
       [-0.36040885,  0.19639975, -0.46473106,  0.02396123,  0.086583  ,
         0.37677354,  0.15946089, -0.18377539,  0.3094174 , -0.1436805 ],
       [-0.05350282, -0.33297654, -0.03663837,  0.48778643, -0.25226742,
        -0.09704394, -0.29284311,  0.35119842,  0.0327335 ,  0.19355386],
       [-0.32778608,  0.26190286,  0.2180077 ,  0.07363993,  0.40769061,
        -0.42946973,  0.26546336, -0.37336012, -0.32043621,  0.22434769],
       [-0.31087932,  0.45739816,  0.45695116, -0.43460661,  0.04347584,
         0.04182818,  0.26135633, -0.36484813,  0.07662087, -0.22729649],
       [ 0.08581871, -0.07158549, -0.1462434 ,  0.15006003, -0.33536787,
         0.22151742,  0.0182535 ,  0.06270858,  0.18453393, -0.16969541],
       [-0.27410261,  0.33963301, -0.05666152, -0.26407532, -0.23661004,
         0.40748955, -0.28104537,  0.2412604 

**9.** Есть массив из 1000 чисел, полученных из генератора случайных чисел, имеющий нормальное распределение. Посчитайте выборочное среднее и выборочную дисперсию. 

In [16]:
X = np.random.normal(loc=5, scale=2., size=1000)
np.mean(X), np.var(X)

(4.9758696821144275, 4.023605407227124)

**10.** Создать матрицу:

$$
\begin{pmatrix}
0 & 1 & 2 & 3 & 4 \\
1 & 2 & 3 & 4 & 0 \\
2 & 3 & 4 & 0 & 1 \\
3 & 4 & 0 & 1 & 2 \\
4 & 0 & 1 & 2 & 3
\end{pmatrix}
$$

In [17]:
def roll(a, i):
    return np.roll(a, -i)

In [18]:
Z = np.zeros((5,5))
Z += np.arange(5)
r = np.arange(5)
np.array(list(map(roll, Z, r)))

array([[0., 1., 2., 3., 4.],
       [1., 2., 3., 4., 0.],
       [2., 3., 4., 0., 1.],
       [3., 4., 0., 1., 2.],
       [4., 0., 1., 2., 3.]])