In [1]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

# 1. Работа с массивами NumPy

**N. Все упражнения ниже нужно делать без использования циклов Python**

**1.** Cоздать вектор

$$(2, \frac{2^2}{2}, \ldots, \frac{2^{20}}{20})$$

Можно использовать функции [np.arange()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html), [np.ones()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html)

In [9]:
def f(i):
    return (2 ** (i + 1)) / (i + 1)

In [10]:
np.fromfunction(f, (20,))

array([2.00000000e+00, 2.00000000e+00, 2.66666667e+00, 4.00000000e+00,
       6.40000000e+00, 1.06666667e+01, 1.82857143e+01, 3.20000000e+01,
       5.68888889e+01, 1.02400000e+02, 1.86181818e+02, 3.41333333e+02,
       6.30153846e+02, 1.17028571e+03, 2.18453333e+03, 4.09600000e+03,
       7.71011765e+03, 1.45635556e+04, 2.75941053e+04, 5.24288000e+04])

**2.** Посчитать:

$$\sum\limits_{i=0}^{5}{0.1^{3i}0.2^{4i}}$$


In [12]:
def f(i):
    return 0.1 ** (3 * i) * 0.2 ** (4 * i)

In [14]:
sum(np.fromfunction(f, (6,)))

1.00000160000256

**3.** Создать нулевую матрицe $8 \times 8$, и заполнить её единицами в шахматном порядке.

In [20]:
x = np.tile(np.array([[0,1],[1,0]]), (4,4))
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


**4.** Есть 5 точек в декартовой системе координат (в виде матрицы $X$ размерностью $5 \times 2$), сконвертируйте эти точки в полярную систему координат.

In [25]:
X = np.random.random((5, 2))
a, b = X[:,0], X[:,1]
R = np.hypot(a, b)
Fi = np.arctan2(b, a)
print(R)
print(Fi)

[0.51931244 0.68810231 1.10421002 0.40811577 0.49327728]
[0.90431749 0.98642545 0.68244035 0.09219764 0.46061412]


**5.** Найдите индексы максимального элемента в случайной матрице $10 \times 10$.

Cм. [np.argmax()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.argmax.html).

In [41]:
X = np.random.random((10, 10))
ind = (np.argmax(X) // 10, np.argmax(X) % 10)
ind

(0, 2)

In [42]:
X[ind]

0.9996327562920637

**6.** Есть 10 точек ($X$) и ещё одна ($y$). Найти в $X$ ближайшую к $y$ точку.

In [49]:
X = np.random.random((10, 2))
y = np.random.random((1, 2))
d0 = np.subtract.outer(X[:,0], y[:,0])
d1 = np.subtract.outer(X[:,1], y[:,1])
np.argmin(np.hypot(d0, d1))

6

**7.** Дана функция:

$$
 \begin{cases}
    x^2 + 2x + 6, & x < 0  \\
    x + 6, & 0 \le x \le 2 \\
    x^2 + 4x - 4, & x \ge 2
 \end{cases}
$$

Постройте массив из её значений на  $-3 \le x \le 3$.

In [83]:
def f(i):
    if i < 0:
        return i ** 2 + 2 * i + 6
    elif i > 2 and i >= 0:
        return i ** 2 + 4 * i - 4
    else:
        return i + 6

In [84]:
rang = np.arange(-3, 4)
rang

array([-3, -2, -1,  0,  1,  2,  3])

In [85]:
np.array(list(map(f, rang)))

array([ 9,  6,  5,  6,  7,  8, 17])

**8.** Из каждого элемента матрицы вычесть среднее арифметическое от всех элементов в соответствующей строке (после чего среднее значение каждой строки должно равняться нулю).

Cм. [np.mean()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.mean.html).

In [258]:
X = np.random.random((10, 10))

In [259]:
res = X - np.mean(X, axis=1).reshape(10, 1)
res

array([[-0.37740105,  0.05921826, -0.01908671, -0.03369362,  0.32989453,
        -0.41690611, -0.19084237,  0.31299635,  0.13272836,  0.20309236],
       [ 0.35276575,  0.40570191, -0.13389113, -0.15099844, -0.3638089 ,
        -0.02161352, -0.50104784,  0.27510172,  0.27038586, -0.13259543],
       [ 0.27052305,  0.35161425, -0.17079902, -0.3302155 ,  0.03468063,
         0.36485059,  0.38279642, -0.44802243, -0.35002116, -0.10540683],
       [-0.05326446, -0.1012672 ,  0.33005368, -0.17390339,  0.32427156,
         0.18081688, -0.38184943, -0.34697872,  0.06972197,  0.15239911],
       [-0.13443184,  0.19045741, -0.26395635,  0.01768436,  0.37407106,
        -0.18643106,  0.31828231, -0.26197444,  0.21633499, -0.27003645],
       [-0.17196287,  0.25842573, -0.30802828,  0.29975617, -0.32953607,
         0.41542471, -0.44484365,  0.19807066,  0.04511883,  0.03757477],
       [-0.00443063, -0.14839325, -0.23091148, -0.10802091, -0.24704749,
         0.4035305 , -0.3806324 ,  0.60243814

**9.** Есть массив из 1000 чисел, полученных из генератора случайных чисел, имеющий нормальное распределение. Посчитайте выборочное среднее и выборочную дисперсию. 

In [224]:
X = np.random.normal(loc=5, scale=2., size=1000)
np.mean(X), np.var(X)

(4.952499823990158, 4.184732463176487)

**10.** Создать матрицу:

$$
\begin{pmatrix}
0 & 1 & 2 & 3 & 4 \\
1 & 2 & 3 & 4 & 0 \\
2 & 3 & 4 & 0 & 1 \\
3 & 4 & 0 & 1 & 2 \\
4 & 0 & 1 & 2 & 3
\end{pmatrix}
$$

In [136]:
def roll(a, i):
    return np.roll(a, -i)

In [139]:
Z = np.zeros((5,5))
Z += np.arange(5)
r = np.arange(5)
np.array(list(map(roll, Z, r)))

array([[0., 1., 2., 3., 4.],
       [1., 2., 3., 4., 0.],
       [2., 3., 4., 0., 1.],
       [3., 4., 0., 1., 2.],
       [4., 0., 1., 2., 3.]])